<?php

declare(strict_types=1);

namespace Tests\Console\Command;

use EzPhp\Console\Command\IdeGenerateCommand;
use PHPUnit\Framework\Attributes\CoversClass;
use Tests\TestCase;

/**
 * Class IdeGenerateCommandTest
 *
 * Tests exercise the --facades option with a local fixture class rather than
 * any of IdeGenerateCommand::KNOWN_FACADES, since which of those classes are
 * actually loaded depends on which optional modules are installed — this
 * framework package's own standalone composer.json does not require any of
 * them (e.g. ez-php/http-client), unlike the monorepo root's autoloader.
 *
 * @package Tests\Console\Command
 */
#[CoversClass(IdeGenerateCommand::class)]
final class IdeGenerateCommandTest extends TestCase
{
    private string $basePath;

    /**
     * @return void
     */
    protected function setUp(): void
    {
        $this->basePath = sys_get_temp_dir() . '/ez-php-ide-generate-' . uniqid();
        mkdir($this->basePath);
    }

    /**
     * @return void
     */
    protected function tearDown(): void
    {
        foreach (glob($this->basePath . '/*.php') ?: [] as $file) {
            unlink($file);
        }
        rmdir($this->basePath);
    }

    /**
     * @return void
     */
    public function test_name_and_description(): void
    {
        $command = new IdeGenerateCommand($this->basePath);

        $this->assertSame('ide:generate', $command->getName());
        $this->assertNotEmpty($command->getDescription());
        $this->assertStringContainsString('ide:generate', $command->getHelp());
    }

    /**
     * @return void
     */
    public function test_generates_file_with_facade_stub_via_facades_option(): void
    {
        $command = new IdeGenerateCommand($this->basePath);
        $output = $this->basePath . '/_ide_helpers.php';

        ob_start();
        $code = $command->handle(['--output=' . $output, '--facades=' . IdeHelperFacadeFixture::class]);
        $printed = (string) ob_get_clean();

        $this->assertSame(0, $code);
        $this->assertFileExists($output);
        $this->assertStringContainsString('Generated: ' . $output, $printed);

        $content = (string) file_get_contents($output);

        // Header and safety markers.
        $this->assertStringContainsString('<?php', $content);
        $this->assertStringContainsString('@noinspection ALL', $content);
        $this->assertStringContainsString('auto-generated by `ez ide:generate`', $content);

        // The fixture's stub block.
        $this->assertStringContainsString('namespace Tests\\Console\\Command {', $content);
        $this->assertStringContainsString('@method static string greet(string $name)', $content);
        $this->assertStringContainsString('@see \\' . IdeHelperFacadeFixture::class, $content);
        $this->assertStringContainsString('class IdeHelperFacadeFixture {}', $content);
    }

    /**
     * @return void
     */
    public function test_respects_output_flag_with_custom_path(): void
    {
        $command = new IdeGenerateCommand($this->basePath);
        $customOutput = $this->basePath . '/custom_helpers.php';

        ob_start();
        $command->handle(['--output=' . $customOutput, '--facades=' . IdeHelperFacadeFixture::class]);
        ob_end_clean();

        $this->assertFileExists($customOutput);
        $this->assertFileDoesNotExist($this->basePath . '/_ide_helpers.php');
    }

    /**
     * @return void
     */
    public function test_defaults_output_to_ide_helpers_php_in_base_path(): void
    {
        $command = new IdeGenerateCommand($this->basePath);

        ob_start();
        $command->handle(['--facades=' . IdeHelperFacadeFixture::class]);
        ob_end_clean();

        $this->assertFileExists($this->basePath . '/_ide_helpers.php');
    }

    /**
     * @return void
     */
    public function test_nonexistent_facade_class_is_silently_skipped(): void
    {
        $command = new IdeGenerateCommand($this->basePath);
        $output = $this->basePath . '/_ide_helpers.php';

        ob_start();
        $command->handle(['--output=' . $output, '--facades=Some\\Totally\\Nonexistent\\ClassXYZ']);
        $printed = (string) ob_get_clean();

        $this->assertStringNotContainsString('Nonexistent', $printed);
    }

    /**
     * @return void
     */
    public function test_extra_facade_without_public_static_methods_produces_no_block(): void
    {
        $command = new IdeGenerateCommand($this->basePath);
        $output = $this->basePath . '/_ide_helpers.php';

        ob_start();
        $code = $command->handle(['--output=' . $output, '--facades=' . IdeHelperEmptyFixture::class]);
        ob_end_clean();

        $this->assertSame(0, $code);
        $content = (string) file_get_contents($output);
        $this->assertStringNotContainsString(IdeHelperEmptyFixture::class, $content);
    }

    /**
     * getMethods(IS_PUBLIC | IS_STATIC) ORs its filter bits (matches "public
     * OR static"), so generateBlock() must explicitly re-check isPublic() &&
     * isStatic() itself — otherwise a private static method would incorrectly
     * appear as a public @method static stub, leaking private API into IDE
     * autocompletion.
     *
     * @return void
     */
    public function test_private_static_method_is_excluded_from_stubs(): void
    {
        $command = new IdeGenerateCommand($this->basePath);
        $output = $this->basePath . '/_ide_helpers.php';

        ob_start();
        $code = $command->handle(['--output=' . $output, '--facades=' . IdeHelperPrivateStaticFixture::class]);
        ob_end_clean();

        $this->assertSame(0, $code);
        $content = (string) file_get_contents($output);

        // The public static method is included; the private one is not.
        $this->assertStringContainsString('publicHelper', $content);
        $this->assertStringNotContainsString('privateHelper', $content);
    }
}

/**
 * Fixture class with a public static method, used to verify the --facades
 * option adds extra classes to the generated stub file.
 *
 * @internal test helper
 */
final class IdeHelperFacadeFixture
{
    public static function greet(string $name): string
    {
        return "Hello, $name!";
    }
}

/**
 * Fixture with one public and one private static method — the private one
 * is genuinely called (via the public one) so it isn't dead code, while
 * verifying it's still excluded from the generated stub.
 *
 * @internal test helper
 */
final class IdeHelperPrivateStaticFixture
{
    public static function publicHelper(): string
    {
        return self::privateHelper();
    }

    private static function privateHelper(): string
    {
        return 'internal';
    }
}

/**
 * Fixture class with no public static methods — generateBlock() must skip it.
 *
 * @internal test helper
 */
final class IdeHelperEmptyFixture
{
    public function instanceMethod(): void
    {
    }
}
